// import { v2 as cloudinary } from "cloudinary";

const cloudinary = require("cloudinary").v2;

cloudinary.config({
  cloud_name: "dtczjjluk",
  api_key: "835125664552836",
  api_secret: "X5QJhL4kQzp_JIQx8c4XJQDy76U",
});

const uploadimage = async (image) => {
  try {
    const results = await cloudinary.uploader.upload(image);
    return results.secure_url;
  } catch (error) {
    return null;
  }
};

const uploadvideo = async (video) => {
  try {
    const results = await cloudinary.uploader.upload(video, {
      resource_type: "video",
    });
    return results.secure_url;
  } catch (error) {
    return null;
  }
};

const data = [
  {
    name: "Handstand Push Up",
    muscle: "Shoulders",
    equipment: "None",
    isvideo: false,
    src: "./images/Handstand Push Up.jpg",
    main: "./videos/Handstand Push Up.jpg",
  },
  {
    name: "Shoulder Taps",
    muscle: "Shoulders",
    equipment: "None",
    isvideo: true,
    src: "./images/Shoulder Taps.jpg",
    main: "./videos/Shoulder Taps.mp4",
  },
  {
    name: "Front Raise (Barbell)",
    muscle: "Shoulders",
    equipment: "Barbell",
    isvideo: true,
    src: "./images/Front Raise (Barbell).jpg",
    main: "./videos/Front Raise (Barbell).mp4",
  },
  {
    name: "Overhead Press (Barbell)",
    muscle: "Shoulders",
    equipment: "Barbell",
    isvideo: true,
    src: "./images/Overhead Press (Barbell).jpg",
    main: "./videos/Overhead Press (Barbell).mp4",
  },
  {
    name: "Push Press",
    muscle: "Shoulders",
    equipment: "Barbell",
    isvideo: true,
    src: "./images/Push Press.jpg",
    main: "./videos/Push Press.mp4",
  },
  {
    name: "Seated Overhead Press (Barbell)",
    muscle: "Shoulders",
    equipment: "Barbell",
    isvideo: false,
    src: "./images/Seated Overhead Press (Barbell).jpg",
    main: "./videos/Seated Overhead Press (Barbell).jpg",
  },
  {
    name: "Standing Military Press (Barbell)",
    muscle: "Shoulders",
    equipment: "Barbell",
    isvideo: true,
    src: "./images/Standing Military Press (Barbell).jpg",
    main: "./videos/Standing Military Press (Barbell).mp4",
  },
  {
    name: "Arnold Press (Dumbbell)",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    isvideo: true,
    src: "./images/Arnold Press (Dumbbell).jpg",
    main: "./videos/Arnold Press (Dumbbell).mp4",
  },
  {
    name: "Chest Supported Y Raise (Dumbbell)",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    isvideo: true,
    src: "./images/Chest Supported Y Raise (Dumbbell).jpg",
    main: "./videos/Chest Supported Y Raise (Dumbbell).mp4",
  },
  {
    name: "Front Raise (Dumbbell)",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    isvideo: true,
    src: "./images/Front Raise (Dumbbell).jpg",
    main: "./videos/Front Raise (Dumbbell).mp4",
  },
  {
    name: "Lateral Raise (Dumbbell)",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    isvideo: true,
    src: "./images/Lateral Raise (Dumbbell).jpg",
    main: "./videos/Lateral Raise (Dumbbell).mp4",
  },
  {
    name: "Overhead Press (Dumbbell)",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    isvideo: true,
    src: "./images/Overhead Press (Dumbbell).jpg",
    main: "./videos/Overhead Press (Dumbbell).mp4",
  },
  {
    name: "Seated Lateral Raise (Dumbbell)",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    isvideo: true,
    src: "./images/Seated Lateral Raise (Dumbbell).jpg",
    main: "./videos/Seated Lateral Raise (Dumbbell).mp4",
  },
  {
    name: "Seated Overhead Press (Dumbbell)",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    isvideo: true,
    src: "./images/Seated Overhead Press (Dumbbell).jpg",
    main: "./videos/Seated Overhead Press (Dumbbell).mp4",
  },
  {
    name: "Shoulder Press (Dumbbell)",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    isvideo: true,
    src: "./images/Shoulder Press (Dumbbell).jpg",
    main: "./videos/Shoulder Press (Dumbbell).mp4",
  },
  {
    name: "Upright Row (Dumbbell)",
    muscle: "Shoulders",
    equipment: "Dumbbell",
    isvideo: true,
    src: "./images/Upright Row (Dumbbell).jpg",
    main: "./videos/Upright Row (Dumbbell).mp4",
  },
  {
    name: "Face Pull",
    muscle: "Shoulders",
    equipment: "Machine",
    isvideo: false,
    src: "./images/Face Pull.jpg",
    main: "./videos/Face Pull.jpg",
  },
  {
    name: "Front Raise (Cable)",
    muscle: "Shoulders",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Front Raise (Cable).jpg",
    main: "./videos/Front Raise (Cable).mp4",
  },
  {
    name: "Lateral Raise (Cable)",
    muscle: "Shoulders",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Lateral Raise (Cable).jpg",
    main: "./videos/Lateral Raise (Cable).mp4",
  },
  {
    name: "Lateral Raise (Machine)",
    muscle: "Shoulders",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Lateral Raise (Machine).jpg",
    main: "./videos/Lateral Raise (Machine).mp4",
  },
  {
    name: "Overhead Press (Smith Machine)",
    muscle: "Shoulders",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Overhead Press (Smith Machine).jpg",
    main: "./videos/Overhead Press (Smith Machine).mp4",
  },
  {
    name: "Seated Shoulder Press (Machine)",
    muscle: "Shoulders",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Seated Shoulder Press (Machine).jpg",
    main: "./videos/Seated Shoulder Press (Machine).mp4",
  },
  {
    name: "Shoulder Press (Machine Plates)",
    muscle: "Shoulders",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Shoulder Press (Machine Plates).jpg",
    main: "./videos/Shoulder Press (Machine Plates).mp4",
  },
  {
    name: "Single Arm Lateral Raise (Cable)",
    muscle: "Shoulders",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Single Arm Lateral Raise (Cable).jpg",
    main: "./videos/Single Arm Lateral Raise (Cable).mp4",
  },
  {
    name: "Upright Row (Cable)",
    muscle: "Shoulders",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Upright Row (Cable).jpg",
    main: "./videos/Upright Row (Cable).mp4",
  },
  {
    name: "Plate Front Raise",
    muscle: "Shoulders",
    equipment: "Plate",
    isvideo: true,
    src: "./images/Plate Front Raise.jpg",
    main: "./videos/Plate Front Raise.mp4",
  },
  {
    name: "Band Pullaparts",
    muscle: "Shoulders",
    equipment: "Resistance Band",
    isvideo: false,
    src: "./images/Band Pullaparts.jpg",
    main: "./videos/Band Pullaparts.jpg",
  },
  {
    name: "Front Raise (Band)",
    muscle: "Shoulders",
    equipment: "Resistance Band",
    isvideo: false,
    src: "./images/Front Raise (Band).jpg",
    main: "./videos/Front Raise (Band).jpg",
  },
  {
    name: "Lateral Raise (Band)",
    muscle: "Shoulders",
    equipment: "Resistance Band",
    isvideo: false,
    src: "./images/Lateral Raise (Band).jpg",
    main: "./videos/Lateral Raise (Band).jpg",
  },
  {
    name: "Diamond Push Up",
    muscle: "Triceps",
    equipment: "None",
    isvideo: false,
    src: "./images/Diamond Push Up.jpg",
    main: "./videos/Diamond Push Up.jpg",
  },
  {
    name: "Floor Triceps Dip",
    muscle: "Triceps",
    equipment: "None",
    isvideo: true,
    src: "./images/Floor Triceps Dip.jpg",
    main: "./videos/Floor Triceps Dip.mp4",
  },
  {
    name: "Pike Pushup",
    muscle: "Triceps",
    equipment: "None",
    isvideo: false,
    src: "./images/Pike Pushup.jpg",
    main: "./videos/Pike Pushup.jpg",
  },
  {
    name: "Ring Dips",
    muscle: "Triceps",
    equipment: "None",
    isvideo: false,
    src: "./images/Ring Dips.jpg",
    main: "./videos/Ring Dips.jpg",
  },
  {
    name: "Bench Press - Close Grip (Barbell)",
    muscle: "Barbell",
    equipment: "None",
    isvideo: true,
    src: "./images/Bench Press - Close Grip (Barbell).jpg",
    main: "./videos/Bench Press - Close Grip (Barbell).mp4",
  },
  {
    name: "JM Press (Barbell)",
    muscle: "Barbell",
    equipment: "None",
    isvideo: true,
    src: "./images/JM Press (Barbell).jpg",
    main: "./videos/JM Press (Barbell).mp4",
  },
  {
    name: "Skullcrusher (Barbell)",
    muscle: "Barbell",
    equipment: "None",
    isvideo: false,
    src: "./images/Skullcrusher (Barbell).jpg",
    main: "./videos/Skullcrusher (Barbell).jpg",
  },
  {
    name: "Triceps Extension (Barbell)",
    muscle: "Barbell",
    equipment: "None",
    isvideo: true,
    src: "./images/Triceps Extension (Barbell).jpg",
    main: "./videos/Triceps Extension (Barbell).mp4",
  },
  {
    name: "Single Arm Tricep Extension (Dumbbell)",
    muscle: "Triceps",
    equipment: "Dumbbell",
    isvideo: true,
    src: "./images/Single Arm Tricep Extension (Dumbbell).jpg",
    main: "./videos/Single Arm Tricep Extension (Dumbbell).mp4",
  },
  {
    name: "Skullcrusher (Dumbbell)",
    muscle: "Triceps",
    equipment: "Dumbbell",
    isvideo: false,
    src: "./images/Skullcrusher (Dumbbell).jpg",
    main: "./videos/Skullcrusher (Dumbbell).jpg",
  },
  {
    name: "Triceps Extension (Dumbbell)",
    muscle: "Triceps",
    equipment: "Dumbbell",
    isvideo: true,
    src: "./images/Triceps Extension (Dumbbell).jpg",
    main: "./videos/Triceps Extension (Dumbbell).mp4",
  },
  {
    name: "Triceps Kickback (Dumbbell)",
    muscle: "Triceps",
    equipment: "Dumbbell",
    isvideo: true,
    src: "./images/Triceps Kickback (Dumbbell).jpg",
    main: "./videos/Triceps Kickback (Dumbbell).mp4",
  },
  {
    name: "Seated Dip Machine",
    muscle: "Triceps",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Seated Dip Machine.jpg",
    main: "./videos/Seated Dip Machine.mp4",
  },
  {
    name: "Single Arm Triceps Pushdown (Cable)",
    muscle: "Triceps",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Single Arm Triceps Pushdown (Cable).jpg",
    main: "./videos/Single Arm Triceps Pushdown (Cable).mp4",
  },
  {
    name: "Triceps Dip",
    muscle: "Triceps",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Triceps Dip.jpg",
    main: "./videos/Triceps Dip.mp4",
  },
  {
    name: "Triceps Dip (Assisted)",
    muscle: "Triceps",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Triceps Dip (Assisted).jpg",
    main: "./videos/Triceps Dip (Assisted).mp4",
  },
  {
    name: "Triceps Dip (Weighted)",
    muscle: "Triceps",
    equipment: "Machine",
    isvideo: false,
    src: "./images/Triceps Dip (Weighted).jpg",
    main: "./videos/Triceps Dip (Weighted).jpg",
  },
  {
    name: "Triceps Extension (Cable)",
    muscle: "Triceps",
    equipment: "Machine",
    isvideo: false,
    src: "./images/Triceps Extension (Cable).jpg",
    main: "./videos/Triceps Extension (Cable).jpg",
  },
  {
    name: "Triceps Extension (Machine)",
    muscle: "Triceps",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Triceps Extension (Machine).jpg",
    main: "./videos/Triceps Extension (Machine).mp4",
  },
  {
    name: "Triceps Kickback (Cable)",
    muscle: "Triceps",
    equipment: "Machine",
    isvideo: false,
    src: "./images/Triceps Kickback (Cable).jpg",
    main: "./videos/Triceps Kickback (Cable).jpg",
  },
  {
    name: "Triceps Pushdown",
    muscle: "Triceps",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Triceps Pushdown.jpg",
    main: "./videos/Triceps Pushdown.mp4",
  },
  {
    name: "Triceps Rope Pushdown",
    muscle: "Triceps",
    equipment: "Machine",
    isvideo: false,
    src: "./images/Triceps Rope Pushdown.jpg",
    main: "./videos/Triceps Rope Pushdown.jpg",
  },
  {
    name: "Bench Dip",
    muscle: "Triceps",
    equipment: "Other",
    isvideo: true,
    src: "./images/Bench Dip.jpg",
    main: "./videos/Bench Dip.mp4",
  },
  {
    name: "Shrug (Barbell)",
    muscle: "Traps",
    equipment: "Barbell",
    isvideo: true,
    src: "./images/Shrug (Barbell).jpg",
    main: "./videos/Shrug (Barbell).mp4",
  },
  {
    name: "Shrug (Cable)",
    muscle: "Traps",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Shrug (Cable).jpg",
    main: "./videos/Shrug (Cable).mp4",
  },
  {
    name: "Shrug (Dumbbell)",
    muscle: "Traps",
    equipment: "Dumbbell",
    isvideo: true,
    src: "./images/Shrug (Dumbbell).jpg",
    main: "./videos/Shrug (Dumbbell).mp4",
  },
  {
    name: "Shrug (Machine)",
    muscle: "Traps",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Shrug (Machine).jpg",
    main: "./videos/Shrug (Machine).mp4",
  },
  {
    name: "Shrug (Smith Machine)",
    muscle: "Traps",
    equipment: "Machine",
    isvideo: true,
    src: "./images/Shrug (Smith Machine).jpg",
    main: "./videos/Shrug (Smith Machine).mp4",
  },
  {
    name: "Upright Row (Barbell)",
    muscle: "Traps",
    equipment: "Barbell",
    isvideo: true,
    src: "./images/Upright Row (Barbell).jpg",
    main: "./videos/Upright Row (Barbell).mp4",
  },
  {
    name: "Lying Neck Curls (Weighted)",
    muscle: "Neck",
    equipment: "Plate",
    isvideo: true,
    src: "./images/Lying Neck Curls (Weighted).jpg",
    main: "./videos/Lying Neck Curls (Weighted).mp4",
  },
  {
    name: "Lying Neck Extension (Weighted)",
    muscle: "Neck",
    equipment: "Plate",
    isvideo: false,
    src: "./images/Lying Neck Extension (Weighted).jpg",
    main: "./videos/Lying Neck Extension (Weighted).jpg",
  },
  {
    name: "Burpee",
    muscle: "Full Body",
    equipment: "None",
    isvideo: true,
    src: "./images/Burpee.jpg",
    main: "./videos/Burpee.mp4",
  },
  {
    name: "Downward Dog",
    muscle: "Full Body",
    equipment: "None",
    isvideo: false,
    src: "./images/Downward Dog.jpg",
    main: "./videos/Downward Dog.jpg",
  },
  {
    name: "Frog Jumps",
    muscle: "Full Body",
    equipment: "None",
    isvideo: false,
    src: "./images/Frog Jumps.jpg",
    main: "./videos/Frog Jumps.jpg",
  },
  {
    name: "Handstand Hold",
    muscle: "Full Body",
    equipment: "None",
    isvideo: false,
    src: "./images/Handstand Hold.jpg",
    main: "./videos/Handstand Hold.jpg",
  },
  {
    name: "Jumping Jack",
    muscle: "Full Body",
    equipment: "None",
    isvideo: false,
    src: "./images/Jumping Jack.jpg",
    main: "./videos/Jumping Jack.jpg",
  },
  {
    name: "Mountain Climber",
    muscle: "Full Body",
    equipment: "None",
    isvideo: false,
    src: "./images/Mountain Climber.jpg",
    main: "./videos/Mountain Climber.jpg",
  },
  {
    name: "One Arm Push Up",
    muscle: "Full Body",
    equipment: "None",
    isvideo: true,
    src: "./images/One Arm Push Up.jpg",
    main: "./videos/One Arm Push Up.mp4",
  },
  {
    name: "Clean",
    muscle: "Full Body",
    equipment: "Barbell",
    isvideo: false,
    src: "./images/Clean.jpg",
    main: "./videos/Clean.jpg",
  },
  {
    name: "Clean and Jerk",
    muscle: "Full Body",
    equipment: "Barbell",
    isvideo: true,
    src: "./images/Clean and Jerk.jpg",
    main: "./videos/Clean and Jerk.mp4",
  },
  {
    name: "Clean and Press",
    muscle: "Full Body",
    equipment: "Barbell",
    isvideo: true,
    src: "./images/Clean and Press.jpg",
    main: "./videos/Clean and Press.mp4",
  },
  {
    name: "Clean Pull",
    muscle: "Full Body",
    equipment: "Barbell",
    isvideo: false,
    src: "./images/Clean Pull.jpg",
    main: "./videos/Clean Pull.jpg",
  },
  {
    name: "Deadlift High Pull",
    muscle: "Full Body",
    equipment: "Barbell",
    isvideo: true,
    src: "./images/Deadlift High Pull.jpg",
    main: "./videos/Deadlift High Pull.mp4",
  },
  {
    name: "Hang Clean",
    muscle: "Full Body",
    equipment: "Barbell",
    isvideo: false,
    src: "./images/Hang Clean.jpg",
    main: "./videos/Hang Clean.jpg",
  },
  {
    name: "Hang Snatch",
    muscle: "Full Body",
    equipment: "Barbell",
    isvideo: false,
    src: "./images/Hang Snatch.jpg",
    main: "./videos/Hang Snatch.jpg",
  },
  {
    name: "Landmine Squat and Press",
    muscle: "Full Body",
    equipment: "Barbell",
    isvideo: false,
    src: "./images/Landmine Squat and Press.jpg",
    main: "./videos/Landmine Squat and Press.jpg",
  },
  {
    name: "Overhead Squat",
    muscle: "Full Body",
    equipment: "Barbell",
    isvideo: false,
    src: "./images/Overhead Squat.jpg",
    main: "./videos/Overhead Squat.jpg",
  },
  {
    name: "Power Clean",
    muscle: "Full Body",
    equipment: "Barbell",
    isvideo: true,
    src: "./images/Power Clean.jpg",
    main: "./videos/Power Clean.mp4",
  },
  {
    name: "Power Snatch",
    muscle: "Full Body",
    equipment: "Barbell",
    isvideo: false,
    src: "./images/Power Snatch.jpg",
    main: "./videos/Power Snatch.jpg",
  },
  {
    name: "Snatch",
    muscle: "Full Body",
    equipment: "Barbell",
    isvideo: false,
    src: "./images/Snatch.jpg",
    main: "./videos/Snatch.jpg",
  },
  {
    name: "Split Jerk",
    muscle: "Full Body",
    equipment: "Barbell",
    isvideo: false,
    src: "./images/Split Jerk.jpg",
    main: "./videos/Split Jerk.jpg",
  },
  {
    name: "Dumbbell Snatch",
    muscle: "Full Body",
    equipment: "Dumbbell",
    isvideo: false,
    src: "./images/Dumbbell Snatch.jpg",
    main: "./videos/Dumbbell Snatch.jpg",
  },
  {
    name: "Kettlebell Clean",
    muscle: "Full Body",
    equipment: "Kettlebell",
    isvideo: false,
    src: "./images/Kettlebell Clean.jpg",
    main: "./videos/Kettlebell Clean.jpg",
  },
  {
    name: "Kettlebell High Pull",
    muscle: "Full Body",
    equipment: "Kettlebell",
    isvideo: false,
    src: "./images/Kettlebell High Pull.jpg",
    main: "./videos/Kettlebell High Pull.jpg",
  },
  {
    name: "Kettlebell Shoulder Press",
    muscle: "Full Body",
    equipment: "Kettlebell",
    isvideo: false,
    src: "./images/Kettlebell Shoulder Press.jpg",
    main: "./videos/Kettlebell Shoulder Press.jpg",
  },
  {
    name: "Kettlebell Snatch",
    muscle: "Full Body",
    equipment: "Kettlebell",
    isvideo: false,
    src: "./images/Kettlebell Snatch.jpg",
    main: "./videos/Kettlebell Snatch.jpg",
  },
  {
    name: "Kettlebell Swing",
    muscle: "Full Body",
    equipment: "Kettlebell",
    isvideo: false,
    src: "./images/Kettlebell Swing.jpg",
    main: "./videos/Kettlebell Swing.jpg",
  },
  {
    name: "Kettlebell Turkish Get Up",
    muscle: "Full Body",
    equipment: "Kettlebell",
    isvideo: false,
    src: "./images/Kettlebell Turkish Get Up.jpg",
    main: "./videos/Kettlebell Turkish Get Up.jpg",
  },
  {
    name: "Thruster (Kettlebell)",
    muscle: "Full Body",
    equipment: "Kettlebell",
    isvideo: false,
    src: "./images/Thruster (Kettlebell).jpg",
    main: "./videos/Thruster (Kettlebell).jpg",
  },
  {
    name: "Muscle Up",
    muscle: "Full Body",
    equipment: "Machine",
    isvideo: false,
    src: "./images/Muscle Up.jpg",
    main: "./videos/Muscle Up.jpg",
  },
  {
    name: "Squat Row",
    muscle: "Full Body",
    equipment: "Machine",
    isvideo: false,
    src: "./images/Squat Row.jpg",
    main: "./videos/Squat Row.jpg",
  },
  {
    name: "Ball Slams",
    muscle: "Full Body",
    equipment: "Other",
    isvideo: false,
    src: "./images/Ball Slams.jpg",
    main: "./videos/Ball Slams.jpg",
  },
  {
    name: "Farmers Walk",
    muscle: "Full Body",
    equipment: "Other",
    isvideo: true,
    src: "./images/Farmers Walk.jpg",
    main: "./videos/Farmers Walk.mp4",
  },
  {
    name: "Sled Push",
    muscle: "Full Body",
    equipment: "Other",
    isvideo: true,
    src: "./images/Sled Push.jpg",
    main: "./videos/Sled Push.mp4",
  },
  {
    name: "Wall Ball",
    muscle: "Full Body",
    equipment: "Other",
    isvideo: false,
    src: "./images/Wall Ball.jpg",
    main: "./videos/Wall Ball.jpg",
  },
];

const newdata = data.map(async (obj) => {
  const newimage = await uploadimage(obj.src);
  var newvideo;
  if (obj.isvideo) {
    newvideo = await uploadvideo(obj.main);
  } else {
    newvideo = await uploadimage(obj.main);
  }
  return {
    ...obj,
    src: newimage,
    main: newvideo,
  };
});

Promise.all(newdata)
  .then((finaldata) => console.log(finaldata))
  .catch((error) => console.log(error));
